pipeline:
  name: F-P
  identifier: FP
  projectIdentifier: Jvts
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: F-S
        identifier: FS
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: F-Stack
                  identifier: FStack
                  spec:
                    provisionerIdentifier: ABC
                    configuration:
                      stackName: S-1
                      connectorRef: AwsConnector
                      region: us-east-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - Lab 1.1.1-CFN.yaml
                              connectorRef: GitHub
                              gitFetchType: Branch
                              branch: main
                      roleArn: ""
                  timeout: 10m
        tags: {}
  variables:
    - name: Aba12345
      type: String
      description: ""
      required: false
      value: <+input>
