AWSTemplateFormatVersion: "2010-09-09"
Description: "Template for S3 Bucket"
Parameters:
  S3bucket:
    Type: String
    Value: <+input>
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3bucket

